// User-facing copy for the box screens. Keys stay stable; only the strings change.
export const copy = {
  boxNameLabel: 'Box name',
  boxNotFoundHeader: 'Box not found',
  cameraStarting: 'Getting the camera ready…',
  cancelButton: 'Cancel',
  colorLabel: 'Color',
  coverPhotoLabel: 'Box photo',
  customStatusLabel: 'Custom',
  deleteBoxButton: 'Delete box',
  doneButton: 'Done',
  editBoxTitle: 'Edit box',
  editMarkersButton: 'Edit markers',
  emptyItemsTitle: 'No items yet',
  goBackButton: 'Go back',
  guestLockNote: "You're viewing as a guest. Ask the owner to invite you to add items.",
  itemsHeading: 'Items',
  keepButton: 'Keep it',
  markerNamePlaceholder: 'e.g. Do not stack, Sell, Donate',
  markersHeading: 'Markers',
  markersSheetHint: 'Handling flags for this box — fragile, open first, heavy… Tap to toggle.',
  missingBoxBody: 'It may have been deleted, or the link is out of date.',
  missingBoxTitle: "We couldn't find that box",
  nameLabel: 'Name',
  newMarkerButton: 'New marker',
  newMarkerTitle: 'Create a new marker',
  newStatusPlaceholder: 'New status…',
  noSearchMatches: 'No items match',
  previewLabel: 'Preview',
  proBadge: 'PRO',
  qrBoxMissingBody: "That box isn't part of this move anymore.",
  qrScreenHint: 'Hold steady — anyone on the move can scan to open it.',
  removeCoverButton: 'Remove photo',
  roomLabel: 'Room',
  searchPlaceholder: 'Search items in this box…',
  showQrFullScreenButton: 'Show full-screen',
  statusNamePlaceholder: 'e.g. Storage unit, Sell, Trash',
  streamItemsButton: 'Stream items',
} as const;
