// User-facing copy for the box screens. Keys stay stable; only the strings change.
export const copy = {
  gettingTheCameraReady: 'Getting the camera ready…',
  removePhoto: 'Remove photo',
  boxPhoto: 'Box photo',
  color: 'Color',
  room: 'Room',
  editBox: 'Edit box',
  boxName: 'Box name',
  items: 'Items',
  noItemsYet: 'No items yet',
  noItemsMatch: 'No items match',
  searchItemsInThisBox: 'Search items in this box…',
  handlingFlagsForThisBox: 'Handling flags for this box — fragile, open first, heavy… Tap to toggle.',
  cancel: 'Cancel',
  createANewMarker: 'Create a new marker',
  done: 'Done',
  markers: 'Markers',
  newMarker: 'New marker',
  eGDoNotStack: 'e.g. Do not stack, Sell, Donate',
  weCouldnTFindThat: "We couldn't find that box",
  itMayHaveBeenDeleted: 'It may have been deleted, or the link is out of date.',
  goBack: 'Go back',
  boxNotFound: 'Box not found',
  showFullScreen: 'Show full-screen',
  custom: 'Custom',
  newStatus: 'New status…',
  preview: 'Preview',
  name: 'Name',
  eGStorageUnitSell: 'e.g. Storage unit, Sell, Trash',
  editMarkers: 'Edit markers',
  streamItems: 'Stream items',
  pro: 'PRO',
  youReViewingAsA: "You're viewing as a guest. Ask the owner to invite you to add items.",
  keepIt: 'Keep it',
  deleteBox: 'Delete box',
  holdSteadyAnyoneOnThe: 'Hold steady — anyone on the move can scan to open it.',
  thatBoxIsnTPart: "That box isn't part of this move anymore.",
} as const;
