// User-facing copy for the dashboard screens. Keys stay stable; only the strings change.
export const copy = {
  colorLabel: 'Color',
  roomLabel: 'Room',
  noRoomsHint: 'Boxes live inside a room. Add your first room to start packing.',
  newRoomButton: 'New room',
  addBoxButton: 'Add box',
  newBoxTitle: 'New box',
  boxNameLabel: "What's in it?",
  boxNamePlaceholder: 'e.g. Kitchen essentials',
  noResults: 'Nothing found',
  iconLabel: 'Icon',
  deleteRoomButton: 'Delete room',
  roomNameLabel: 'Room name',
  roomNamePlaceholder: 'e.g. Garage, Nursery, Office',
  destinationLabel: 'Destination (optional)',
  destinationPlaceholder: 'Where it lands — e.g. NYC bedroom',
  cascadeDeleteForbiddenTitle: 'Only the owner can delete a room with boxes',
  cascadeDeleteForbiddenBody: 'Ask the move owner, or move/empty its boxes first.',
  keepButton: 'Keep it',
  okButton: 'OK',
  cancelButton: 'Cancel',
  deleteAllButton: 'Delete all',
  searchLabel: "Find an item — “Where's my…?”",
  addRoomButton: 'Add room',
  viewerLockNote: 'Viewers can browse and scan — ask the owner to add boxes.',
  estimatedValueLabel: 'Estimated value',
  boxesStatLabel: 'Boxes',
  itemsStatLabel: 'Items',
  suggestionsPrefix: 'Try',
  findHeading: 'Find',
  searchPlaceholder: "Where's my…?",
} as const;
