// User-facing copy for the dashboard screens. Keys stay stable; only the strings change.
export const copy = {
  addBoxButton: 'Add box',
  addRoomButton: 'Add room',
  boxesStatLabel: 'Boxes',
  boxNameLabel: "What's in it?",
  boxNamePlaceholder: 'e.g. Kitchen essentials',
  clearFiltersLabel: 'Clear filters',
  cancelButton: 'Cancel',
  cascadeDeleteForbiddenBody: 'Ask the move owner, or move/empty its boxes first.',
  cascadeDeleteForbiddenTitle: 'Only the owner can delete a room with boxes',
  colorLabel: 'Color',
  deleteAllButton: 'Delete all',
  deleteRoomButton: 'Delete room',
  destinationLabel: 'Destination (optional)',
  destinationPlaceholder: 'Where it lands — e.g. NYC bedroom',
  estimatedValueLabel: 'Estimated value',
  filterRoomsLabel: 'Rooms',
  filterStatusLabel: 'Status',
  findHeading: 'Find',
  iconLabel: 'Icon',
  itemsStatLabel: 'Items',
  keepButton: 'Keep it',
  newBoxTitle: 'New box',
  newRoomButton: 'New room',
  noResults: 'Nothing found',
  noResultsFiltered: 'No items or boxes match these filters.',
  noteMatchPrefix: 'Note: ',
  noRoomsHint: 'Boxes live inside a room. Add your first room to start packing.',
  okButton: 'OK',
  roomLabel: 'Room',
  roomNameLabel: 'Room name',
  roomNamePlaceholder: 'e.g. Garage, Nursery, Office',
  searchLabel: "Find an item — “Where's my…?”",
  searchPlaceholder: "Where's my…?",
  suggestionsPrefix: 'Try',
  viewerLockNote: 'Viewers can browse and scan — ask the owner to add boxes.',
} as const;
