// User-facing copy for the dashboard screens. Keys stay stable; only the strings change.
export const copy = {
  color: 'Color',
  room: 'Room',
  boxesLiveInsideARoom: 'Boxes live inside a room. Add your first room to start packing.',
  newRoom: 'New room',
  addBox: 'Add box',
  newBox: 'New box',
  whatSInIt: "What's in it?",
  eGKitchenEssentials: 'e.g. Kitchen essentials',
  nothingFound: 'Nothing found',
  icon: 'Icon',
  deleteRoom: 'Delete room',
  roomName: 'Room name',
  eGGarageNurseryOffice: 'e.g. Garage, Nursery, Office',
  destinationOptional: 'Destination (optional)',
  whereItLandsEG: 'Where it lands — e.g. NYC bedroom',
  onlyTheOwnerCanDelete: 'Only the owner can delete a room with boxes',
  askTheMoveOwnerOr: 'Ask the move owner, or move/empty its boxes first.',
  keepIt: 'Keep it',
  ok: 'OK',
  cancel: 'Cancel',
  deleteAll: 'Delete all',
  findAnItemWhereS: "Find an item — “Where's my…?”",
  addRoom: 'Add room',
  viewersCanBrowseAndScan: 'Viewers can browse and scan — ask the owner to add boxes.',
  estimatedValue: 'Estimated value',
  boxes: 'Boxes',
  items: 'Items',
  try: 'Try',
  find: 'Find',
  whereSMy: "Where's my…?",
} as const;
