// User-facing copy for the moves screens. Keys stay stable; only the strings change.
export const copy = {
  accountTitle: 'Account',
  addressPlaceholder: 'Search an address',
  appName: 'Tuck',
  cancelButton: 'Cancel',
  createMoveButton: 'Create a move',
  createMoveTitle: 'Create move',
  datePlaceholder: 'Pick a date',
  deleteAccountButton: 'Delete account',
  deleteAccountConfirmBody:
    "This permanently deletes your account and any moves saved to it. This can't be undone.",
  deleteAccountConfirmTitle: 'Delete account?',
  deleteAccountFailedTitle: 'Could not delete account',
  deleteButton: 'Delete',
  deleteMoveConfirmTitle: 'Delete move?',
  editMoveTitle: 'Edit move',
  fromLabel: 'From',
  fromOptionalLabel: 'From (optional)',
  fromPlaceholder: 'Current address',
  guestAccountNote:
    "You're using Tuck as a guest — your moves are saved on this device only. Sign in to back them up and sync across your devices.",
  joinButton: 'Join',
  joinHint: 'Paste the invite link or code a friend shared with you.',
  joinPlaceholder: 'Paste invite link or code',
  joinTitle: 'Join a move',
  libraryTitle: 'Your moves',
  moveNameLabel: 'Move name',
  moveNamePlaceholder: 'e.g. NYC Move',
  nameLabel: 'Name',
  newMoveButton: 'New move',
  newMoveNamePlaceholder: 'e.g. Apartment move',
  saveChangesButton: 'Save changes',
  taglineText: 'Pack fast. Find anything. Share the load.',
  targetDateLabel: 'Target date',
  targetDateOptionalLabel: 'Target date (optional)',
  targetDatePlaceholder: 'Pick a move date',
  toOptionalLabel: 'To (optional)',
  toPlaceholder: 'New address',
} as const;
