// User-facing copy for the moves screens. Keys stay stable; only the strings change.
export const copy = {
  deleteAccount: 'Delete account',
  youReUsingTuckAs:
    'You’re using Tuck as a guest — your moves are saved on this device only. Sign in to back them up and sync across your devices.',
  account: 'Account',
  deleteAccount2: 'Delete account?',
  thisPermanentlyDeletesYourAccount:
    'This permanently deletes your account and any moves saved to it. This can’t be undone.',
  couldNotDeleteAccount: 'Could not delete account',
  cancel: 'Cancel',
  delete: 'Delete',
  from: 'From',
  targetDate: 'Target date',
  saveChanges: 'Save changes',
  editMove: 'Edit move',
  moveName: 'Move name',
  eGNycMove: 'e.g. NYC Move',
  currentAddress: 'Current address',
  newAddress: 'New address',
  pickAMoveDate: 'Pick a move date',
  pasteTheInviteLinkOr: 'Paste the invite link or code a friend shared with you.',
  join: 'Join',
  joinAMove: 'Join a move',
  pasteInviteLinkOrCode: 'Paste invite link or code',
  tuck: 'Tuck',
  packFastFindAnythingShare: 'Pack fast. Find anything. Share the load.',
  createAMove: 'Create a move',
  yourMoves: 'Your moves',
  deleteMove: 'Delete move?',
  createMove: 'Create move',
  newMove: 'New move',
  name: 'Name',
  eGApartmentMove: 'e.g. Apartment move',
  fromOptional: 'From (optional)',
  searchAnAddress: 'Search an address',
  toOptional: 'To (optional)',
  targetDateOptional: 'Target date (optional)',
  pickADate: 'Pick a date',
} as const;
