// User-facing copy for the moves screens. Keys stay stable; only the strings change.
export const copy = {
  deleteAccountButton: 'Delete account',
  youReUsingTuckAs:
    'You’re using Tuck as a guest — your moves are saved on this device only. Sign in to back them up and sync across your devices.',
  accountTitle: 'Account',
  deleteAccountConfirmTitle: 'Delete account?',
  thisPermanentlyDeletesYourAccount:
    'This permanently deletes your account and any moves saved to it. This can’t be undone.',
  deleteAccountFailedTitle: 'Could not delete account',
  cancelButton: 'Cancel',
  deleteButton: 'Delete',
  fromLabel: 'From',
  targetDateLabel: 'Target date',
  saveChangesButton: 'Save changes',
  editMoveTitle: 'Edit move',
  moveNameLabel: 'Move name',
  moveNamePlaceholder: 'e.g. NYC Move',
  fromPlaceholder: 'Current address',
  toPlaceholder: 'New address',
  targetDatePlaceholder: 'Pick a move date',
  joinHint: 'Paste the invite link or code a friend shared with you.',
  joinButton: 'Join',
  joinTitle: 'Join a move',
  joinPlaceholder: 'Paste invite link or code',
  appName: 'Tuck',
  tagline: 'Pack fast. Find anything. Share the load.',
  createMoveButton: 'Create a move',
  libraryTitle: 'Your moves',
  deleteMoveConfirmTitle: 'Delete move?',
  createMoveTitle: 'Create move',
  newMoveButton: 'New move',
  nameLabel: 'Name',
  newMoveNamePlaceholder: 'e.g. Apartment move',
  fromOptionalLabel: 'From (optional)',
  addressPlaceholder: 'Search an address',
  toOptionalLabel: 'To (optional)',
  targetDateOptionalLabel: 'Target date (optional)',
  datePlaceholder: 'Pick a date',
} as const;
