// User-facing copy for the stream screens. Keys stay stable; only the strings change.
export const copy = {
  switchToStream: 'Switch to Stream',
  pro: 'PRO',
  snapAnItemThenName: 'Snap an item, then name it',
  itemName: 'Item name',
  value: 'Value',
  quantity: 'Quantity',
  remove: 'Remove',
  fixThisItem: 'Fix this item',
  eGCastIronSkillet: 'e.g. Cast iron skillet',
  tapToFix: 'Tap to fix',
  added: 'Added',
  undo: 'Undo',
  nothingYetSnapYourFirst: 'Nothing yet — snap your first item.',
  thatDoesnTLookRight: "That doesn't look right — tap to fix",
  thisSession: 'This session',
  hmmDidnTCatchA: "Hmm — didn't catch a name. Tap to type it.",
  singleItem: 'Single item',
  niceStreak: 'Nice streak!',
  keepGoing: 'Keep going',
  done: 'Done',
  close: 'Close',
  noBoxesYetAddA: 'No boxes yet — add a box first, then capture into it.',
  back: 'Back',
} as const;
