// User-facing copy for the stream screens. Keys stay stable; only the strings change.
export const copy = {
  addedLabel: 'Added',
  backButton: 'Back',
  captureHint: 'Snap an item, then name it',
  closeButton: 'Close',
  doneButton: 'Done',
  emptyLedger: 'Nothing yet — snap your first item.',
  fixItemTitle: 'Fix this item',
  itemNameLabel: 'Item name',
  itemNamePlaceholder: 'e.g. Cast iron skillet',
  keepGoingButton: 'Keep going',
  ledgerTitle: 'This session',
  listeningHint: "Listening… tap the button when you're done",
  micPermissionBody:
    'Tuck needs microphone and speech access to add items by voice. Turn them on in Settings › Tuck, then try again.',
  micPermissionTitle: 'Microphone access needed',
  micUnavailableBody:
    "This device has no speech recognizer, so items can't be added by voice. Snap or type them instead.",
  micUnavailableTitle: "Voice capture isn't available",
  needsFixHint: "That doesn't look right — tap to fix",
  noBoxesHint: 'No boxes yet — add a box first, then capture into it.',
  noNameHeardHint: "Hmm — didn't catch a name. Tap to type it.",
  proBadge: 'PRO',
  quantityLabel: 'Quantity',
  removeButton: 'Remove',
  simulatedDictationNote: 'No microphone here — dictation is simulated in this development build',
  singleItemMode: 'Single item',
  snapModeHint: 'Snap, then say what it is',
  streakTitle: 'Nice streak!',
  switchToStreamButton: 'Switch to Stream',
  tapToFixHint: 'Tap to fix',
  undoButton: 'Undo',
  valueLabel: 'Value',
  voiceModeHint: 'Tap, then name everything in the box',
} as const;
