// User-facing copy for the stream screens. Keys stay stable; only the strings change.
export const copy = {
  addedLabel: 'Added',
  backButton: 'Back',
  captureHint: 'Snap an item, then name it',
  closeButton: 'Close',
  doneButton: 'Done',
  emptyLedger: 'Nothing yet — snap your first item.',
  fixItemTitle: 'Fix this item',
  itemNameLabel: 'Item name',
  itemNamePlaceholder: 'e.g. Cast iron skillet',
  keepGoingButton: 'Keep going',
  ledgerTitle: 'This session',
  needsFixHint: "That doesn't look right — tap to fix",
  noBoxesHint: 'No boxes yet — add a box first, then capture into it.',
  noNameHeardHint: "Hmm — didn't catch a name. Tap to type it.",
  proBadge: 'PRO',
  quantityLabel: 'Quantity',
  removeButton: 'Remove',
  singleItemMode: 'Single item',
  streakTitle: 'Nice streak!',
  switchToStreamButton: 'Switch to Stream',
  tapToFixHint: 'Tap to fix',
  undoButton: 'Undo',
  valueLabel: 'Value',
} as const;
